### ISSUE TITLE
Parameterized functions marked as invalid

### ISSUE THREAD

**Issue by mak3** [ealap/vscode-language-ttcn#26]
**Describe the bug**
It looks like "<" right after function name triggers some validator.

**To Reproduce**
`function test<type someType>(someType p_param)`

**Expected behavior**
Parameterized functions not marked as invalid

**Screenshots**
![paramFunctions](https://user-images.githubusercontent.com/19293740/58981208-372ba580-87d2-11e9-8db4-d66a22a22789.PNG)

**Comment by ealap** [comment]
Is this format of parametrized identifier unique to your use case or is it standard TTCN-3?

**Comment by mak3** [comment]
It is in standard https://www.etsi.org/deliver/etsi_es/202700_202799/202784/01.06.01_60/es_202784v010601p.pdf#page=11
